service: aws-lambda-example

provider:
  name: aws
  runtime: java21
  region: ${opt:region, 'eu-north-1'}
  stage: ${opt:stage, 'dev'}

functions:
  AwsLambdaExampleFunction:
    handler: org.example.StreamLambdaHandler::handleRequest
    memorySize: 512
    timeout: 30
    events:
      - http:
          path: /{proxy+}
          method: any

plugins:
  - serverless-deployment-bucket

resources:
  Outputs:
    AwsLambdaExampleApi:
      Description: URL for application
      Value: !Sub 'https://${AWS::StackName}.execute-api.${AWS::Region}.amazonaws.com/${self:provider.stage}/courses'
