service: aws-lambda-example

provider:
  name: aws
  runtime: java21
  region: eu-north-1

functions:
  AwsLambdaExampleFunction:
    handler: org.example.StreamLambdaHandler::handleRequest
    memorySize: 512
    timeout: 30
    events:
      - http:
          path: /{proxy+}
          method: any

plugins:
  - serverless-deployment-bucket